updat

diff --git a/.github/workflows/workflow.yml b/.github/workflows/workflow.yml
--- a/.github/workflows/workflow.yml
+++ b/.github/workflows/workflow.yml
@@ -24,18 +24,22 @@ jobs:
     - name: Checkout code
       uses: actions/checkout@v2
 
-    - name: Set Environment Variable
+    - name: Set Environment Variables
       run: |
-        echo "export environment=${{ github.event.inputs.environment }}" >> $GITHUB_ENV
-        echo "export version_number=${{ github.event.inputs.version_number }}" >> $GITHUB_ENV
+        echo "export environment=${{ github.event.inputs.environment }}" >> $HOME/.bashrc
+        echo "export version_number=${{ github.event.inputs.version_number }}" >> $HOME/.bashrc
 
     - name: Run Script based on Version
       run: |
-        if [ "${{ github.event.inputs.version_number }}" -eq 1 ]; then
-          bash data1/v1.sh
-        elif [ "${{ github.event.inputs.version_number }}" -eq 2 ]; then
-          bash data2/v2.sh
+        source $HOME/.bashrc
+        version_folder="data${version_number}"
+        if [[ ! $version_number =~ ^[0-9]+$ ]]; then
+          echo "Invalid version number specified."
+          exit 1
+        fi
+        if [ -d "$version_folder" ]; then
+          bash "$version_folder/v${version_number}.sh"
         else
-          echo "Unsupported version number specified."
+          echo "Folder for version number $version_number not found."
           exit 1
         fi
